## 端口号 上下文路径
server:
  port: 8084
  servlet:
    context-path: /crm1
## 数据源配置
spring:
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/crm4?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
  ## freemarker
  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
    template-loader-path: classpath:/views/
  ## 启用热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  ## 发送邮件配置
  mail:
    host: smtp.qq.com     #默认平台服务地址无需更改
    username: 504529528@qq.com   #自己邮箱号
    password: fuzitznxpokvcadh    #这是我们在刚刚开启POP3/SMTP服务时收到的授权码(如果忘了把服务重开一次!)
    default-encoding: utf-8 #改编码格式
    protocol: smtp
    port: 25 #端口号
    properties:
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
## mybatis 配置
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.yjxxt.bean;com.yjxxt.query;com.yjxxt.dto
  configuration:
    map-underscore-to-camel-case: true
## pageHelper 分页
pagehelper:
  helper-dialect: mysql
## 设置 dao 日志打印级别
logging:
  level:
    com:
      yjxxt:
        mapper: debug



